<?php

namespace Database\Seeders;

use App\Models\DocumentChecklistTemplate;
use Illuminate\Database\Seeder;

class DocumentChecklistTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // SETUP PROGRAM REQUIREMENTS

            // SET 1: Prior to conduct of TNA
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-tna-01',
                'document_name' => 'Filled-out TNA Form 01 (form to be provided by CSTC/PSTC)',
                'group_name' => 'General Requirements',
                'is_mandatory' => true,
                'sort_order' => 1,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-gad-assessment',
                'document_name' => 'GAD Assessment (GWP)',
                'group_name' => 'General Requirements',
                'is_mandatory' => true,
                'sort_order' => 2,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-gad-checklist',
                'document_name' => 'GAD Checklist for Science and Technology Interventions in MSMEs',
                'group_name' => 'General Requirements',
                'is_mandatory' => true,
                'sort_order' => 3,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-hazard-hunter',
                'document_name' => 'Hazard Hunter',
                'group_name' => 'General Requirements',
                'is_mandatory' => true,
                'sort_order' => 4,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-mayors-permit',
                'document_name' => "Recent Mayor's Permit indicating the firm's line of business",
                'group_name' => 'Business Documents',
                'is_mandatory' => true,
                'sort_order' => 5,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-dti-registration',
                'document_name' => 'DTI registration for sole proprietorship',
                'group_name' => 'Business Documents',
                'is_mandatory' => false,
                'sort_order' => 6,
                'applicability_rules' => ['business_types' => ['Sole Proprietorship']],
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-bir-registration',
                'document_name' => 'BIR Registration',
                'group_name' => 'Business Documents',
                'is_mandatory' => true,
                'sort_order' => 7,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-blank-or',
                'document_name' => 'Photocopy of Blank Official Receipt',
                'group_name' => 'Business Documents',
                'is_mandatory' => true,
                'sort_order' => 8,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-equipment-quotations',
                'document_name' => '3 valid equipment quotations from 3 different suppliers, originally signed with preference to the lowest bidder',
                'group_name' => 'Technical & Equipment Documents',
                'is_mandatory' => true,
                'sort_order' => 9,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-lease-contract',
                'document_name' => 'Lease contract for rented manufacturing space or equivalent',
                'group_name' => 'Business Documents',
                'is_mandatory' => false,
                'sort_order' => 10,
                'applicability_rules' => ['space_ownership' => 'Rented'],
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-corp-board-res',
                'document_name' => 'Notarized Board Resolution authorizing the availment of assistance & designating the approved signatory for the funding assistance',
                'group_name' => 'For Corporations / Cooperatives',
                'is_mandatory' => false,
                'sort_order' => 11,
                'applicability_rules' => ['business_types' => ['Corporation', 'Cooperative', 'Partnership']],
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-corp-sec-cda',
                'document_name' => 'SEC or CDA registration',
                'group_name' => 'For Corporations / Cooperatives',
                'is_mandatory' => false,
                'sort_order' => 12,
                'applicability_rules' => ['business_types' => ['Corporation', 'Cooperative', 'Partnership']],
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-corp-aoi',
                'document_name' => 'Articles of Incorporation/Cooperation',
                'group_name' => 'For Corporations / Cooperatives',
                'is_mandatory' => false,
                'sort_order' => 13,
                'applicability_rules' => ['business_types' => ['Corporation', 'Cooperative', 'Partnership']],
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-corp-sec-cert',
                'document_name' => "Secretary's certificate of incumbent officers",
                'group_name' => 'For Corporations / Cooperatives',
                'is_mandatory' => false,
                'sort_order' => 14,
                'applicability_rules' => ['business_types' => ['Corporation', 'Cooperative', 'Partnership']],
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-fs-financial-position',
                'document_name' => "A. Statement of Financial Position (with Proponent's Notarized Sworn Statement)",
                'group_name' => 'Financial Statements (past 3 years for Small/Medium, 1 year for Micro)',
                'is_mandatory' => true,
                'sort_order' => 15,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-fs-financial-operation',
                'document_name' => "B. Statement of Financial Operation (with Proponent's Notarized Sworn Statement)",
                'group_name' => 'Financial Statements (past 3 years for Small/Medium, 1 year for Micro)',
                'is_mandatory' => true,
                'sort_order' => 16,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-fs-cash-flows',
                'document_name' => "C. Statement of Financial Cash Flows (with Proponent's Notarized Sworn Statement)",
                'group_name' => 'Financial Statements (past 3 years for Small/Medium, 1 year for Micro)',
                'is_mandatory' => true,
                'sort_order' => 17,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-fs-changes-equity',
                'document_name' => "D. Statement of Changes in Owner's Equity (with Proponent's Notarized Sworn Statement)",
                'group_name' => 'Financial Statements (past 3 years for Small/Medium, 1 year for Micro)',
                'is_mandatory' => true,
                'sort_order' => 18,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-fs-notes',
                'document_name' => "E. Notes to Financial Statements (with Proponent's Notarized Sworn Statement)",
                'group_name' => 'Financial Statements (past 3 years for Small/Medium, 1 year for Micro)',
                'is_mandatory' => true,
                'sort_order' => 19,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET1',
                'phase_title' => 'SET 1 (To be compiled and reviewed prior to conduct of TNA)',
                'item_code' => 'setup-s1-loi-commitment',
                'document_name' => 'Letter of Intent for SETUP Assistance, stating commitment to refund the assistance and cover the insurance cost of equipment.',
                'group_name' => 'General Requirements',
                'is_mandatory' => true,
                'sort_order' => 20,
                'applicability_rules' => null,
            ],

            // SET 2: During proposal preparation
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET2',
                'phase_title' => 'SET 2 (To be compiled and check during proposal preparation)',
                'item_code' => 'setup-s2-biodata',
                'document_name' => 'Bio-data of the approved signatory',
                'group_name' => 'Signatory & Identification Documents',
                'is_mandatory' => true,
                'sort_order' => 21,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET2',
                'phase_title' => 'SET 2 (To be compiled and check during proposal preparation)',
                'item_code' => 'setup-s2-govt-id',
                'document_name' => 'Photocopy of valid government issued ID of the approved signatory with 3 signatures',
                'group_name' => 'Signatory & Identification Documents',
                'is_mandatory' => true,
                'sort_order' => 22,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET2',
                'phase_title' => 'SET 2 (To be compiled and check during proposal preparation)',
                'item_code' => 'setup-s2-brgy-cert',
                'document_name' => 'Barangay certification of permanent residence of the approved signatory',
                'group_name' => 'Signatory & Identification Documents',
                'is_mandatory' => true,
                'sort_order' => 23,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET2',
                'phase_title' => 'SET 2 (To be compiled and check during proposal preparation)',
                'item_code' => 'setup-s2-omnibus',
                'document_name' => 'Omnibus affidavit stating: 1) None of organizers/officials is an agent, 2) No bad debt, 3) No previous DOST accountabilities, 4) Information in AFR true & correct, 5) Truthfulness of stated facts',
                'group_name' => 'Signatory & Identification Documents',
                'is_mandatory' => true,
                'sort_order' => 24,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET2',
                'phase_title' => 'SET 2 (To be compiled and check during proposal preparation)',
                'item_code' => 'setup-s2-tna-form-4',
                'document_name' => 'TNA Form 4',
                'group_name' => 'TNA Technical Documents',
                'is_mandatory' => true,
                'sort_order' => 25,
                'applicability_rules' => null,
            ],

            // SET 3: Post-approval & deliberation
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-request-funds',
                'document_name' => 'Request for Release of Funds',
                'group_name' => 'Fund Release & Financial Requirements',
                'is_mandatory' => true,
                'sort_order' => 26,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-lbp-waiver',
                'document_name' => 'Waiver and Authorization to Tag LBP Account',
                'group_name' => 'Fund Release & Financial Requirements',
                'is_mandatory' => true,
                'sort_order' => 27,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-payee-form',
                'document_name' => 'Payee Data Form',
                'group_name' => 'Fund Release & Financial Requirements',
                'is_mandatory' => true,
                'sort_order' => 28,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-notarized-moa',
                'document_name' => 'Notarized and signed MOA',
                'group_name' => 'Legal & Agreement Documents',
                'is_mandatory' => true,
                'sort_order' => 29,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-pre-project-sheet',
                'document_name' => 'Pre- Project Implementation Sheet',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 30,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-notice-approval',
                'document_name' => 'Notice of Approval',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 31,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-approved-lib',
                'document_name' => 'Approved Line-Item Budget',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 32,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-ard-approval',
                'document_name' => 'Recommending Approval of ARD',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 33,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-psto-endorsement',
                'document_name' => 'Endorsement letter from C/PSTO',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 34,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-final-proposal',
                'document_name' => 'Final Copy of Project Proposal',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 35,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-rtec-report',
                'document_name' => 'RTEC Report',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 36,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-risk-register',
                'document_name' => 'Candidate Risk Register',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 37,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'SETUP',
                'phase_code' => 'SET3',
                'phase_title' => 'SET 3 (To be compiled and check after project proposal deliberation and approval)',
                'item_code' => 'setup-s3-seti-scorecard',
                'document_name' => 'SETI Scorecard',
                'group_name' => 'Project Implementation & Approvals',
                'is_mandatory' => true,
                'sort_order' => 38,
                'applicability_rules' => null,
            ],

            // GIA PROGRAM REQUIREMENTS

            // Stage 01: Proposal Submission, Evaluation, and Approval
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-loi',
                'document_name' => 'Letter of Intent or for Collaboration duly signed by the Head of IA',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 101,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-endorsement',
                'document_name' => 'Endorsement Letter from the concerned PSTO/Division',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 102,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-eligibility',
                'document_name' => 'Accomplished eligibility checklist for project leader',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 103,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-dost-form-4',
                'document_name' => 'DOST Form 4.A (R&D Project) or DOST Form 4.B (Non-R&D Project Proposal)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 104,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-dost-form-6',
                'document_name' => 'DOST Form 6 (Line Item Budget) with counterpart funds',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 105,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-dost-form-5',
                'document_name' => 'DOST Form 5 (Workplan)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 106,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-rtec-report',
                'document_name' => 'RTEC Report',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 107,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-seti-scorecard',
                'document_name' => 'SETI Scorecard',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 108,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-gad-checklist',
                'document_name' => 'GAD Checklist',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 109,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-moa-resolution',
                'document_name' => 'Memorandum of Agreement (MOA) with resolution to sign (if LGU/NGO)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => false,
                'sort_order' => 110,
                'applicability_rules' => ['org_types' => ['LGU', 'NGO', 'PO', 'Barangay LGU']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-cfa',
                'document_name' => 'Certificate of Funds Availability (CFA)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 111,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-ched-accreditation',
                'document_name' => 'CHED Accreditation',
                'group_name' => 'Additional documents for Higher Education Institutions',
                'is_mandatory' => false,
                'sort_order' => 112,
                'applicability_rules' => ['org_types' => ['HEI', 'SUC']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-good-track-record',
                'document_name' => 'Certification of Good Track Record with DOST',
                'group_name' => 'Additional documents for Higher Education Institutions',
                'is_mandatory' => false,
                'sort_order' => 113,
                'applicability_rules' => ['org_types' => ['HEI', 'SUC']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-sec-cda-dole',
                'document_name' => 'SEC/CDA/DOLE Registration and Articles of Incorporation/Cooperation with By-Laws',
                'group_name' => 'Additional documents for (NGOs/CSOs/Private Sector) - without transfer of funds',
                'is_mandatory' => false,
                'sort_order' => 114,
                'applicability_rules' => ['org_types' => ['NGO', 'CSO', 'Private', 'PO']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-audited-fs',
                'document_name' => 'Audited Financial Statements for the past three (3) years',
                'group_name' => 'Additional documents for (NGOs/CSOs/Private Sector) - without transfer of funds',
                'is_mandatory' => false,
                'sort_order' => 115,
                'applicability_rules' => ['org_types' => ['NGO', 'CSO', 'Private', 'PO']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-sworn-affidavit',
                'document_name' => 'Sworn Affidavit of no relationship',
                'group_name' => 'Additional documents for (NGOs/CSOs/Private Sector) - without transfer of funds',
                'is_mandatory' => false,
                'sort_order' => 116,
                'applicability_rules' => ['org_types' => ['NGO', 'CSO', 'Private', 'PO']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-secretary-cert',
                'document_name' => "Secretary's Certificate of directors and officers",
                'group_name' => 'Additional documents for (NGOs/CSOs/Private Sector) - without transfer of funds',
                'is_mandatory' => false,
                'sort_order' => 117,
                'applicability_rules' => ['org_types' => ['NGO', 'CSO', 'Private', 'PO']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '01',
                'phase_title' => 'Stage 01: Project Proposal Submission, Evaluation, and Approval',
                'item_code' => 'gia-s1-board-resolution',
                'document_name' => 'Board Resolution for the engagement of the NGO/CSO/PO for the project, assignment of the official representative, and authority to sign related documents and transact with DOST Davao Region',
                'group_name' => 'Additional documents for (NGOs/CSOs/Private Sector) - without transfer of funds',
                'is_mandatory' => false,
                'sort_order' => 118,
                'applicability_rules' => ['org_types' => ['NGO', 'CSO', 'Private', 'PO']],
            ],

            // Stage 02: Releasing of Project Funds
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-request-release',
                'document_name' => 'Request for the release of funds',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 201,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-payee-data-form',
                'document_name' => 'Payee Data Form',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 202,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-notarized-moa',
                'document_name' => 'Notarized Memorandum of Agreement',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 203,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-rtec-report',
                'document_name' => 'RTEC Report',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 204,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-dost-form-4b',
                'document_name' => 'DOST Form 4.B (Non-R&D Project Proposal)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 205,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-dost-form-6',
                'document_name' => 'DOST Form 6 (Line Item Budget) with counterpart funds',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 206,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-dost-form-5',
                'document_name' => 'DOST Form 5 (Workplan)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 207,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-cfa',
                'document_name' => 'Certificate of Funds Availability (CFA)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 208,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-loi',
                'document_name' => 'Letter of Intent',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 209,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-dost-form-7',
                'document_name' => 'DOST Form 7 (Clearance from the DOST or the Funding Agency on previously funded, completed projects)',
                'group_name' => 'General Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 210,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-brgy-bond',
                'document_name' => 'Bond of Barangay Captain and Barangay Treasurer with an amount that can cover the funds to be granted',
                'group_name' => 'Additional documents for Barangay LGUs',
                'is_mandatory' => false,
                'sort_order' => 211,
                'applicability_rules' => ['org_types' => ['Barangay LGU', 'LGU']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-brgy-certification',
                'document_name' => 'Certification or other equivalent documents of previously handled projects through downloaded funds from external sources, preferably government agencies, as applicable',
                'group_name' => 'Additional documents for Barangay LGUs',
                'is_mandatory' => false,
                'sort_order' => 212,
                'applicability_rules' => ['org_types' => ['Barangay LGU', 'LGU']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-ched-accreditation',
                'document_name' => 'CHED Accreditation',
                'group_name' => 'Additional documents for Higher Education Institutions',
                'is_mandatory' => false,
                'sort_order' => 213,
                'applicability_rules' => ['org_types' => ['HEI', 'SUC']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '02',
                'phase_title' => 'Stage 02: Releasing of Project Funds',
                'item_code' => 'gia-s2-good-track-record',
                'document_name' => 'Certification of Good Track Record with DOST',
                'group_name' => 'Additional documents for Higher Education Institutions',
                'is_mandatory' => false,
                'sort_order' => 214,
                'applicability_rules' => ['org_types' => ['HEI', 'SUC']],
            ],

            // Stage 03: Project Monitoring
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-10',
                'document_name' => 'DOST Form 10 (Executive Summary of Technical Progress Report)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => true,
                'sort_order' => 301,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-8',
                'document_name' => 'DOST Form 8 (List of Personnel Involved)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => true,
                'sort_order' => 302,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-9',
                'document_name' => 'DOST Form 9 (List of Equipment Purchased, as applicable)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => false,
                'sort_order' => 303,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-11',
                'document_name' => 'COA-received DOST Form 11 (Financial Report)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => true,
                'sort_order' => 304,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-13',
                'document_name' => 'DOST Form 13 (Schedule of Accounts Payable)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => false,
                'sort_order' => 305,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-coa-checks',
                'document_name' => 'COA-received Reports of Checks Issued',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => true,
                'sort_order' => 306,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-coa-disbursements',
                'document_name' => 'COA-received Reports of Disbursements',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => true,
                'sort_order' => 307,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-12',
                'document_name' => 'DOST Form 12 (Fund Utilization Report) (For Private)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => false,
                'sort_order' => 308,
                'applicability_rules' => ['org_types' => ['Private', 'NGO', 'CSO', 'PO']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-far-6',
                'document_name' => 'DBM URS-generated FAR 6 (Statement of Approved Budget, Utilizations, Disbursements and Balances for TRUST Receipts - for LGUs, NGAs, SUCs only)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => false,
                'sort_order' => 309,
                'applicability_rules' => ['org_types' => ['LGU', 'Barangay LGU', 'NGA', 'SUC', 'HEI']],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-14',
                'document_name' => 'DOST Form 14 (Report of Income/Interest Earned, as applicable)',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => false,
                'sort_order' => 310,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-jev-equipment',
                'document_name' => 'Journal Entry Voucher for the Purchase of Equipment and Recognition of Depreciation Expenses',
                'group_name' => 'Documentary Reports: From Implementing Agency (IA)',
                'is_mandatory' => false,
                'sort_order' => 311,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '03',
                'phase_title' => 'Stage 03: Project Monitoring',
                'item_code' => 'gia-s3-dost-form-15',
                'document_name' => 'DOST Form 15 (Project Monitoring and Field Evaluation Report)',
                'group_name' => 'Documentary Reports: From Monitoring Agency (DOST Davao Region)',
                'is_mandatory' => true,
                'sort_order' => 312,
                'applicability_rules' => null,
            ],

            // Stage 04: Extension & Reprogramming
            [
                'program_type' => 'GIA',
                'phase_code' => '04',
                'phase_title' => 'Stage 04: Extension & Reprogramming',
                'item_code' => 'gia-s4-request-extension',
                'document_name' => 'Letter of Request with justifications for extension/change of implementation date, duly signed by the Head of IA',
                'group_name' => 'Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 401,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '04',
                'phase_title' => 'Stage 04: Extension & Reprogramming',
                'item_code' => 'gia-s4-endorsement-monitoring',
                'document_name' => 'Endorsement Letter from the Monitoring Unit',
                'group_name' => 'Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 402,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '04',
                'phase_title' => 'Stage 04: Extension & Reprogramming',
                'item_code' => 'gia-s4-latest-dost-form-11',
                'document_name' => 'Latest DOST Form 11 (if project has transferred funds, must also attach the latest FR of the utilization of downloaded funds to IA)',
                'group_name' => 'Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 403,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '04',
                'phase_title' => 'Stage 04: Extension & Reprogramming',
                'item_code' => 'gia-s4-latest-dost-form-10',
                'document_name' => 'Latest DOST Form 10 (Executive Summary of Technical Progress Report) (for extension)',
                'group_name' => 'Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 404,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '04',
                'phase_title' => 'Stage 04: Extension & Reprogramming',
                'item_code' => 'gia-s4-dost-form-6',
                'document_name' => 'DOST Form 6 (Proposed Line-Item-Budget)',
                'group_name' => 'Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 405,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '04',
                'phase_title' => 'Stage 04: Extension & Reprogramming',
                'item_code' => 'gia-s4-updated-dost-form-5',
                'document_name' => 'Updated DOST Form 5 (Workplan)',
                'group_name' => 'Documentary Requirements',
                'is_mandatory' => true,
                'sort_order' => 406,
                'applicability_rules' => null,
            ],

            // Stage 05: Project Liquidation and Completion
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-endorsement-complete',
                'document_name' => 'Endorsement Letter from Head of IA for the submission of complete set of documents',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 501,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-dost-form-11-updated',
                'document_name' => 'DOST Form 11 - updated Financial Report (FR) duly signed as to approval by the Implementing Agency (IA)',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 502,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-dost-form-18',
                'document_name' => 'DOST Form 18 - Terminal Financial Report duly signed as to approval by the Implementing Agency (IA) and duly stamped received by COA',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 503,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-coa-checks',
                'document_name' => 'COA-received Report of Checks Issued',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 504,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-coa-disbursement',
                'document_name' => 'COA-received Report of Disbursement',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 505,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-or-unexpended',
                'document_name' => 'Official Receipt (OR) of Unexpended Balance (as applicable)',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 506,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-lib-realignment',
                'document_name' => 'Line-Item Budget / Realignment (as applicable)',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 507,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-dost-form-8',
                'document_name' => 'DOST Form 8: List of Personnel Involved',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 508,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-dost-form-9',
                'document_name' => 'DOST Form 9: List of Equipment Purchased',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 509,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-dost-form-17',
                'document_name' => 'DOST Form 17: Executive Summary of Terminal Accomplishment Report',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 510,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-narrative-report',
                'document_name' => 'Narrative Report with photo documentation of the implemented projects/activities',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => true,
                'sort_order' => 511,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-proof-outputs',
                'document_name' => 'Proof of Outputs: Inspection Report, publishable or pre-print manuscript, evidence of IP protection filing; (as applicable)',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 512,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-beneficiaries-list',
                'document_name' => 'List of Beneficiaries signifying acceptance/acknowledgement of the project/funds/goods/services received, (as applicable)',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 513,
                'applicability_rules' => null,
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-purchase-docs',
                'document_name' => 'All documents related to the purchase of equipment',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 514,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-insurance-equipment',
                'document_name' => 'Insurance of the procured equipment (CTC)',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 515,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-jev-depreciation',
                'document_name' => 'JEV on Depreciation pertaining to the procured equipment, if applicable',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 516,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-par-ics',
                'document_name' => 'PAR/ICS issued by IA',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 517,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-inventory-inspection',
                'document_name' => 'Inventory of Equipment and Inspection report prepared by IA, conforme by Monitoring Unit',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 518,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-schedule-depreciation',
                'document_name' => 'Schedule of Depreciation and Net Book Value of procured equipment',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 519,
                'applicability_rules' => ['has_equipment' => true],
            ],
            [
                'program_type' => 'GIA',
                'phase_code' => '05',
                'phase_title' => 'Stage 05: Project Liquidation and Completion',
                'item_code' => 'gia-s5-dost-form-14',
                'document_name' => 'DOST Form 14 (Report of Income/Interest Earned, as applicable)',
                'group_name' => 'Documentary Requirements: From Implementing Agency',
                'is_mandatory' => false,
                'sort_order' => 520,
                'applicability_rules' => null,
            ],
        ];

        foreach ($templates as $data) {
            DocumentChecklistTemplate::updateOrCreate(
                ['item_code' => $data['item_code']],
                $data
            );
        }
    }
}
