<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypeSeeder extends Seeder
{
    /**
     * Builds a document_types row, filling in the common defaults so each
     * entry below only needs to state what's non-default.
     */
    private function doc(array $overrides): array
    {
        return array_merge([
            'group' => null,
            'description' => null,
            'instructions' => null,
            'template_url' => null,
            'applicable_business_types' => null,
            'applicable_business_sizes' => null,
            'applicable_gia_categories' => null,
            'is_required' => true,
            'is_applicant_visible' => true,
        ], $overrides);
    }

    public function run(): void
    {
        $documentTypes = [

            // Auto-generated by the system — never shown as an applicant upload item
            $this->doc([
                'name' => 'Project Proposal Form (SETUP Form 001)',
                'set_number' => 'PROPOSAL',
                'applicable_program' => 'SETUP',
                'is_applicant_visible' => false,
            ]),
            // GIA sibling of the row above. GiaSubmissionService::submit()
            // looks up DocumentType::where('set_number', 'PROPOSAL')
            // ->where('applicable_program', 'GIA') to attach the
            // auto-generated proposal PDF snapshot — without this row that
            // lookup returns null and every GIA submission throws
            // "GIA proposal DocumentType (set_number=PROPOSAL) is not
            // seeded."
            $this->doc([
                'name' => 'Project Proposal Form (GIA)',
                'set_number' => 'PROPOSAL',
                'applicable_program' => 'GIA',
                'is_applicant_visible' => false,
            ]),

            // ---------------------------------------------------------
            // SET1 — applicant-facing checklist (Business Documents)
            // ---------------------------------------------------------
            $this->doc([
                'name' => "Recent Mayor's Permit",
                'group' => 'Business Documents',
                'description' => "The permit must indicate the firm's current line of business.",
                'instructions' => "Upload a clear scanned copy of your valid Mayor's/Business Permit indicating the firm's line of business.",
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'DTI Registration Certificate',
                'group' => 'Business Documents',
                'description' => 'Certificate of Business Name Registration issued by DTI.',
                'instructions' => 'Upload Department of Trade and Industry (DTI) Certificate of Business Name Registration for sole proprietorship.',
                'set_number' => 'SET1',
                // SETUP-only: this document is scoped by applicable_business_types,
                // a SETUP-specific concept. Was 'BOTH', which made it silently
                // required for GIA submissions too even though no GIA checklist
                // item ever asked the applicant to upload it, causing every GIA
                // submission to fail with "Missing required document(s)".
                'applicable_program' => 'SETUP',
                'applicable_business_types' => ['SOLE-PROPRIETORSHIP'],
            ]),
            $this->doc([
                'name' => 'SEC Registration Certificate',
                'group' => 'Business Documents',
                'description' => 'Certificate of SEC Registration (Corporation/Partnership) or CDA Registration (Cooperative).',
                'instructions' => 'Upload SEC or CDA Registration Certificate.',
                'set_number' => 'SET1',
                // SETUP-only — see note on 'DTI Registration Certificate' above.
                // GIA has its own equivalent, category-scoped item below:
                // 'SEC/CDA/DOLE Registration and Articles of Incorporation/Cooperation
                // with By-Laws' (applicable_gia_categories: PRIVATE-SECTOR).
                'applicable_program' => 'SETUP',
                'applicable_business_types' => ['PARTNERSHIP', 'CORPORATION', 'COOPERATIVE'],
            ]),
            $this->doc([
                'name' => 'BIR Registration',
                'group' => 'Business Documents',
                'description' => 'Bureau of Internal Revenue Certificate of Registration (Form 2303).',
                'instructions' => 'Upload official BIR Certificate of Registration (Form 2303).',
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Photocopy of Blank Official Receipt',
                'group' => 'Business Documents',
                'description' => 'Provide a clear scanned copy or photo of a blank official receipt.',
                'instructions' => 'Upload a clear scanned copy or photo of a sample blank official receipt.',
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Three (3) Valid Equipment Quotations',
                'group' => 'Business Documents',
                'description' => 'From 3 different suppliers, originally signed with preference to the lowest bidder.',
                'instructions' => 'Obtain 3 valid equipment quotations from 3 different suppliers, originally signed with preference to the lowest bidder. Combine into a single PDF before uploading.',
                'set_number' => 'SET1',
                'applicable_program' => 'SETUP',
            ]),
            $this->doc([
                'name' => 'Lease Contract for Rented Manufacturing Space',
                'group' => 'Business Documents',
                'description' => 'Required if manufacturing space is rented.',
                'instructions' => 'Upload the lease contract for rented manufacturing space or equivalent (if space is rented).',
                'set_number' => 'SET1',
                'applicable_program' => 'SETUP',
                'is_required' => false,
            ]),

            // SET1 — Corporation / Cooperative Documents
            $this->doc([
                'name' => 'Notarized Board Resolution',
                'group' => 'Corporation / Cooperative Documents',
                'description' => 'Authorizing the availment of assistance & designating the approved signatory.',
                'instructions' => 'Notarized Board Resolution authorizing the availment of assistance & designating the approved signatory for the funding assistance.',
                'set_number' => 'SET1',
                // SETUP-only — see note on 'DTI Registration Certificate' above.
                // GIA (Private Sector) has its own equivalent item below: 'Board
                // Resolution for the engagement of the NGO/CSO/PO for the project...'
                'applicable_program' => 'SETUP',
                'applicable_business_types' => ['CORPORATION', 'COOPERATIVE'],
            ]),
            $this->doc([
                'name' => 'Articles of Incorporation / Cooperation',
                'group' => 'Corporation / Cooperative Documents',
                'description' => 'Official Articles of Incorporation or Articles of Cooperation with By-Laws.',
                'instructions' => 'Upload Articles of Incorporation / Cooperation.',
                'set_number' => 'SET1',
                // SETUP-only — see note on 'DTI Registration Certificate' above.
                // GIA (Private Sector) covers this within the combined
                // 'SEC/CDA/DOLE Registration and Articles of Incorporation/
                // Cooperation with By-Laws' item below.
                'applicable_program' => 'SETUP',
                'applicable_business_types' => ['CORPORATION', 'COOPERATIVE'],
            ]),
            $this->doc([
                'name' => "Secretary's Certificate of Incumbent Officers",
                'group' => 'Corporation / Cooperative Documents',
                'description' => 'Certified list of incumbent corporate or cooperative officers.',
                'instructions' => "Upload Secretary's certificate of incumbent officers.",
                'set_number' => 'SET1',
                // SETUP-only — see note on 'DTI Registration Certificate' above.
                // GIA (Private Sector) has its own equivalent item below:
                // "Secretary's Certificate of directors and officers".
                'applicable_program' => 'SETUP',
                'applicable_business_types' => ['CORPORATION', 'COOPERATIVE'],
            ]),

            // SET1 — Financial Documents
            $this->doc([
                'name' => 'Statement of Financial Position',
                'group' => 'Financial Documents',
                'description' => 'For Small & Medium Enterprises (past 3 years) or Microenterprises (at least 1 year), with notarized Sworn Statement.',
                'instructions' => 'Audited Statement of Financial Position (Balance Sheet) together with notarized Sworn Statement that all information provided are correct and true.',
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Statement of Financial Operations',
                'group' => 'Financial Documents',
                'description' => 'For Small & Medium Enterprises (past 3 years) or Microenterprises (at least 1 year), with notarized Sworn Statement.',
                'instructions' => 'Audited Statement of Financial Operation (Income Statement) together with notarized Sworn Statement.',
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Statement of Cash Flows',
                'group' => 'Financial Documents',
                'description' => 'For Small & Medium Enterprises (past 3 years) or Microenterprises (at least 1 year), with notarized Sworn Statement.',
                'instructions' => 'Statement of Financial Cash Flows together with notarized Sworn Statement.',
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => "Statement of Changes in Owner's Equity",
                'group' => 'Financial Documents',
                'description' => 'For Small & Medium Enterprises (past 3 years) or Microenterprises (at least 1 year), with notarized Sworn Statement.',
                'instructions' => "Statement of Changes in Owner's Equity together with notarized Sworn Statement.",
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Notes to Financial Statements',
                'group' => 'Financial Documents',
                'description' => 'For Small & Medium Enterprises (past 3 years) or Microenterprises (at least 1 year), with notarized Sworn Statement.',
                'instructions' => 'Notes to Financial Statements accompanying audited financial statements.',
                'set_number' => 'SET1',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Letter of Intent for SETUP Assistance',
                'group' => 'Additional Documents',
                'description' => 'Stating commitment to refund the assistance and cover the insurance cost of equipment.',
                'instructions' => 'Letter of Intent for SETUP Assistance, stating commitment to refund the assistance and cover the insurance cost of equipment.',
                'set_number' => 'SET1',
                'applicable_program' => 'SETUP',
            ]),

            // SET1 — internal, not on applicant checklist
            $this->doc(['name' => 'Filled-out TNA Form 01', 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'GAD Assessment (GWP)', 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'GAD Checklist for S&T Interventions in MSMEs', 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Hazard Hunter', 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'is_applicant_visible' => false]),

            // ---------------------------------------------------------
            // SET2 — applicant-facing (Additional Documents)
            // ---------------------------------------------------------
            $this->doc([
                'name' => 'Bio-data of the Approved Signatory',
                'group' => 'Additional Documents',
                'description' => 'Curriculum Vitae / Bio-data of the approved signatory.',
                'instructions' => 'Upload Bio-data / CV of the approved signatory.',
                'set_number' => 'SET2',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Valid Government-issued ID of the Approved Signatory',
                'group' => 'Additional Documents',
                'description' => 'Must include 3 specimen signatures.',
                'instructions' => 'Photocopy of valid government-issued ID of the approved signatory with 3 specimen signatures.',
                'set_number' => 'SET2',
                'applicable_program' => 'BOTH',
            ]),
            $this->doc([
                'name' => 'Barangay Certificate of Permanent Residence',
                'group' => 'Additional Documents',
                'description' => 'Barangay certification of permanent residence of the approved signatory.',
                'instructions' => 'Upload Barangay certification of permanent residence of the approved signatory.',
                'set_number' => 'SET2',
                'applicable_program' => 'BOTH',
            ]),

            // SET2 — internal
            $this->doc(['name' => 'Omnibus Affidavit', 'set_number' => 'SET2', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'TNA Form 4', 'set_number' => 'SET2', 'applicable_program' => 'SETUP', 'is_applicant_visible' => false]),

            // ---------------------------------------------------------
            // SET3 — all internal / post-approval workflow
            // ---------------------------------------------------------
            $this->doc(['name' => 'Request for Release of Funds', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Waiver and Authorization to Tag LBP Account', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Payee Data Form', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Notarized and Signed MOA', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Pre-Project Implementation Sheet', 'set_number' => 'SET3', 'applicable_program' => 'SETUP', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Notice of Approval', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Approved Line-Item Budget', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Recommending Approval of ARD', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Endorsement Letter from C/PSTO', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Final Copy of Project Proposal', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'RTEC Report', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'Candidate Risk Register', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),
            $this->doc(['name' => 'SETI Scorecard', 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'is_applicant_visible' => false]),

            // ---------------------------------------------------------
            // GIA1 — applicant-facing checklist (Core Documents, all proponent categories)
            // ---------------------------------------------------------
            $this->doc([
                'name' => 'Letter of Intent or for Collaboration duly signed by the Head of IA',
                'group' => 'GIA Core Documents',
                'description' => 'Signed by the head of the implementing agency / organization.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
            ]),
            $this->doc([
                'name' => 'Complete Project Proposal Form',
                'group' => 'GIA Core Documents',
                'description' => 'Duly accomplished project proposal following the standard DOST format.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
            ]),
            $this->doc([
                'name' => 'Project Leader Eligibility Checklist',
                'group' => 'GIA Core Documents',
                'description' => 'Checklist of eligibility requirements for the designated project leader.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
            ]),
            $this->doc([
                'name' => 'Workplan and Implementation Schedule',
                'group' => 'GIA Core Documents',
                'description' => 'Detailed workplan and gantt chart of project activities.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
            ]),
            $this->doc([
                'name' => 'Certificate of Availability of Funds / Counterpart Funding',
                'group' => 'GIA Core Documents',
                'description' => 'Proof of available counterpart funds for the proposed project.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
            ]),

            // GIA1 — Private Sector only
            $this->doc([
                'name' => 'SEC/CDA/DOLE Registration and Articles of Incorporation/Cooperation with By-Laws',
                'group' => 'Additional Documents',
                'description' => 'SEC, CDA, or DOLE registration and Articles of Incorporation or Cooperation with By-Laws.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['PRIVATE-SECTOR'],
            ]),
            $this->doc([
                'name' => 'Audited Financial Statements for the past three (3) years',
                'group' => 'Additional Documents',
                'description' => 'Audited financial statements covering the past three (3) years.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['PRIVATE-SECTOR'],
            ]),
            $this->doc([
                'name' => 'Sworn Affidavit of no relationship',
                'group' => 'Additional Documents',
                'description' => 'Notarized sworn affidavit declaring no prohibited relationship.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['PRIVATE-SECTOR'],
            ]),
            $this->doc([
                'name' => "Secretary's Certificate of directors and officers",
                'group' => 'Additional Documents',
                'description' => 'Certified list of current directors and officers of the organization.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['PRIVATE-SECTOR'],
            ]),
            $this->doc([
                'name' => 'Board Resolution for the engagement of the NGO/CSO/PO for the project, assignment of the official representative, and authority to sign related documents and transact with DOST Davao Region',
                'group' => 'Additional Documents',
                'description' => 'Official Board Resolution authorizing project engagement, official representative, signing authority, and DOST transactions.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['PRIVATE-SECTOR'],
            ]),

            // GIA1 — Higher Education Institution only
            $this->doc([
                'name' => 'CHED Accreditation',
                'group' => 'Additional Documents',
                'description' => 'Current accreditation issued or recognized by the Commission on Higher Education (CHED).',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['HEI'],
            ]),
            $this->doc([
                'name' => 'Certification of Good Track Record with DOST',
                'group' => 'Additional Documents',
                'description' => 'Certification confirming satisfactory track record and compliance with DOST.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['HEI'],
            ]),

            // GIA1 — Barangay LGU only
            $this->doc([
                'name' => 'Bond of Barangay Captain and Barangay Treasurer with an amount that can cover the funds to be granted',
                'group' => 'Additional Documents',
                'description' => 'Official bond of Barangay Captain and Treasurer sufficient to cover granted funds.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['BARANGAY-LGU'],
            ]),
            $this->doc([
                'name' => 'Certification or other equivalent documents of previously handled projects through downloaded funds from external sources, preferably government agencies, as applicable',
                'group' => 'Additional Documents',
                'description' => 'Certification of previously handled projects funded through downloaded external sources.',
                'set_number' => 'GIA1',
                'applicable_program' => 'GIA',
                'applicable_gia_categories' => ['BARANGAY-LGU'],
                'is_required' => false,
            ]),
        ];

        foreach ($documentTypes as $type) {
            DocumentType::create($type);
        }
    }
}
