<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypeSeeder extends Seeder
{
    public function run(): void
    {
        $documentTypes = [
            // Auto-generated by the system — never shown as an applicant upload item
            [
                'name' => 'Project Proposal Form (SETUP Form 001)',
                'group' => null,
                'description' => null,
                'set_number' => 'PROPOSAL',
                'applicable_program' => 'SETUP',
                'applicable_business_types' => null,
                'applicable_gia_categories' => null,
                'is_required' => true,
                'is_applicant_visible' => false,
            ],

            // SET1 — applicant-facing checklist (Business Documents)
            ['name' => "Recent Mayor's Permit", 'group' => 'Business Documents', 'description' => "The permit must indicate the firm's current line of business.", 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'DTI Registration Certificate', 'group' => 'Business Documents', 'description' => 'Certificate of Business Name Registration issued by DTI.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => ['SOLE-PROPRIETORSHIP'], 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'SEC Registration Certificate', 'group' => 'Business Documents', 'description' => 'Certificate of Registration issued by SEC.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => ['PARTNERSHIP', 'CORPORATION'], 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'BIR Registration', 'group' => 'Business Documents', 'description' => 'Upload the latest BIR Certificate of Registration.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Photocopy of Blank Official Receipt', 'group' => 'Business Documents', 'description' => 'Provide a clear scanned copy or photo of a blank official receipt.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Three (3) Valid Equipment Quotations', 'group' => 'Business Documents', 'description' => 'Combine quotations from three different suppliers in one PDF before uploading.', 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Lease Contract for Rented Manufacturing Space', 'group' => 'Business Documents', 'description' => 'Upload only when the manufacturing space is rented.', 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => false, 'is_applicant_visible' => true],

            // SET1 — Corporation / Cooperative Documents
            ['name' => 'Notarized Board Resolution', 'group' => 'Corporation / Cooperative Documents', 'description' => 'Board authority approving the SETUP application and its approved signatory.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => ['CORPORATION', 'COOPERATIVE'], 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Articles of Incorporation / Cooperation', 'group' => 'Corporation / Cooperative Documents', 'description' => 'Upload the organization articles filed with the appropriate registration office.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => ['CORPORATION', 'COOPERATIVE'], 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ["name" => "Secretary's Certificate of Incumbent Officers", 'group' => 'Corporation / Cooperative Documents', 'description' => 'Provide the current list of officers certified by the corporate secretary.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => ['CORPORATION', 'COOPERATIVE'], 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],

            // SET1 — Financial Documents
            ['name' => 'Statement of Financial Position', 'group' => 'Financial Documents', 'description' => 'Upload the latest available statement.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Statement of Financial Operations', 'group' => 'Financial Documents', 'description' => 'Upload the latest available statement.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Statement of Cash Flows', 'group' => 'Financial Documents', 'description' => 'Upload the latest available statement.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ["name" => "Statement of Changes in Owner's Equity", 'group' => 'Financial Documents', 'description' => 'Upload the latest available statement.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Notes to Financial Statements', 'group' => 'Financial Documents', 'description' => 'Upload the notes that accompany the submitted financial statements.', 'set_number' => 'SET1', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Letter of Intent for SETUP Assistance', 'group' => 'Additional Documents', 'description' => 'Signed letter expressing intent to avail of SETUP assistance.', 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],

            // SET1 — internal, not on applicant checklist
            ['name' => 'Filled-out TNA Form 01', 'group' => null, 'description' => null, 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'GAD Assessment (GWP)', 'group' => null, 'description' => null, 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'GAD Checklist for S&T Interventions in MSMEs', 'group' => null, 'description' => null, 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Hazard Hunter', 'group' => null, 'description' => null, 'set_number' => 'SET1', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],

            // SET2 — applicant-facing (Additional Documents)
            ['name' => 'Bio-data of the Approved Signatory', 'group' => 'Additional Documents', 'description' => 'Provide the current bio-data of the person authorized to sign for the enterprise.', 'set_number' => 'SET2', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Valid Government-issued ID of the Approved Signatory', 'group' => 'Additional Documents', 'description' => 'The uploaded copy must include three specimen signatures.', 'set_number' => 'SET2', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],
            ['name' => 'Barangay Certificate of Permanent Residence', 'group' => 'Additional Documents', 'description' => 'Certificate of permanent residence of the approved signatory.', 'set_number' => 'SET2', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => true],

            // SET2 — internal
            ['name' => 'Omnibus Affidavit', 'group' => null, 'description' => null, 'set_number' => 'SET2', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'TNA Form 4', 'group' => null, 'description' => null, 'set_number' => 'SET2', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],

            // SET3 — all internal / post-approval workflow, never shown to applicant at registration
            ['name' => 'Request for Release of Funds', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Waiver and Authorization to Tag LBP Account', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Payee Data Form', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Notarized and Signed MOA', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Pre-Project Implementation Sheet', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'SETUP', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Notice of Approval', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Approved Line-Item Budget', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Recommending Approval of ARD', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Endorsement Letter from C/PSTO', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Final Copy of Project Proposal', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'RTEC Report', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'Candidate Risk Register', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
            ['name' => 'SETI Scorecard', 'group' => null, 'description' => null, 'set_number' => 'SET3', 'applicable_program' => 'BOTH', 'applicable_business_types' => null, 'applicable_gia_categories' => null, 'is_required' => true, 'is_applicant_visible' => false],
        ];

        foreach ($documentTypes as $type) {
            DocumentType::create($type);
        }
    }
}
